### ISSUE TITLE
On shutdown: Exception in OpenTK.dll

### ISSUE THREAD

**Issue by MarcSeebold** [SpagAachen/Ballz#12]
Version: Master branch, "Update Ballz.sln" (34de104b0d56cfb3733ed58ec86ad729c37c078d)
How to reproduce: Close the program.
Configuration: Win10 x64 (German), MSVC2k13 (German)
"Ein Ausnahmefehler des Typs "OpenTK.Graphics.GraphicsContextException" ist in OpenTK.dll aufgetreten."

**Comment by Martin-Schultz** [comment]
something strange is happening on linux too.
When i close the Programm, my screenresolution is not always restored. But this is happening for a while now and i just thought i was doing something wrong.

i thing this might be caused by the gameloop as i think it should stop all rendering attempts as soon as the close signal occurs (i will look at my other OpenTK project to confirm that it is caused by the way OpenTK is used)

**Comment by LukasBoersma** [comment]
This is no longer an issue due to the switch to DirectX.
