### ISSUE TITLE
Travis: Mac builds

### ISSUE THREAD

**Issue by MarcSeebold** [SpagAachen/Ballz#6]
Automated mac builds

**Comment by Martin-Schultz** [comment]
So i just created a branch for this task where i added osx to the travis configuration.
osx builds are passing but im not shure how to separate linux and osx builds since both are built on travis by just running two jobs.
one solution would be to use separate branches for osx and linux.
i personally would prefer a solution without having separate branches, but since the osx build takes 10 minutes, it might be a good idea to compile less frequent on osx

**Comment by LukasBoersma** [comment]
Travis supports a configuration matrix, so it will build different configurations for every commit. I think you already set up everything correctly, [Travis is building both Linux and OSX](https://travis-ci.org/SpagAachen/SpagAachen/Ballz/builds/86102954).
We don't pay for the build time and Travis keeps compiling new commits even if the old builds are not yet finished, so it should not make the Linux builds any slower.

So, merge back to master or should we wait until we see if the game actually runs on OSX?

**Comment by Martin-Schultz** [comment]
In general i think we could merge back to master.
The only thing i still have in mind is the mgcb project, as i would really like to integrate it in the build process. This would requiere the build servers to have the monogame pipeline installed.
for appveyor we could use chocolatey, but we can discuss this in #8 

As for the configuration matrix, if one of the jobs fails, can we determine which one it was? Now we can just take a look at the image, but once we merge back i think the build status would represent linux & osx. 

Caching seems not to work properly on osx as for the build mono is downloaded from external sources and that takes around 6 minutes.
